branch-defaults:
  main:
    environment: caitlin-website
environment-defaults:
  caitlin-web:
    branch: null
    repository: null
  caitlin-website:
    branch: null
    repository: null
global:
  application_name: caitlin-blog
  default_ec2_keyname: caitlin-key
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
