branch-defaults:
  main:
    environment: caitlin-web
environment-defaults:
  caitlin-web:
    branch: null
    repository: null
global:
  application_name: caitlin-blog
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
